package com.arttrainer.toolbox;

import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.app.Service;
import android.content.Intent;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.os.Build;
import android.os.Handler;
import android.os.IBinder;
import android.os.Looper;
import android.provider.Settings;
import android.view.Gravity;
import android.view.MotionEvent;
import android.view.View;
import android.view.WindowManager;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import android.widget.Toast;
import java.io.File;

public class OverlayService extends Service {
    public static final String ACTION_START="com.arttrainer.toolbox.overlay.START", ACTION_STOP="com.arttrainer.toolbox.overlay.STOP", ACTION_SHOW_BUBBLE="com.arttrainer.toolbox.overlay.SHOW_BUBBLE", ACTION_SHOW_PREVIEW="com.arttrainer.toolbox.overlay.SHOW_PREVIEW", ACTION_REFRESH_SETTINGS="com.arttrainer.toolbox.overlay.REFRESH";
    public static final String EXTRA_CAPTURE_PATH="capturePath", EXTRA_PREVIEW_MODE="previewMode";
    private static final String CHANNEL="arttrainer_overlay"; private static final int NOTIF=9101; private static volatile boolean running=false;
    private WindowManager wm; private View bubble,panel,preview; private WindowManager.LayoutParams bubbleLp; private Handler ui; private long lastTap=0; private boolean dragging=false; private final Runnable dimTask=()->setBubbleAlpha(true);
    public static boolean isRunning(){return running;}
    @Override public void onCreate(){super.onCreate();wm=(WindowManager)getSystemService(WINDOW_SERVICE);ui=new Handler(Looper.getMainLooper());createChannel();startForeground(NOTIF,notification());running=true;}
    @Override public int onStartCommand(Intent i,int flags,int startId){if(i==null)return START_STICKY;String a=i.getAction();if(ACTION_STOP.equals(a)){safeRestore();removeAll();stopSelf();return START_NOT_STICKY;}if(ACTION_SHOW_PREVIEW.equals(a)){showPreview(i.getStringExtra(EXTRA_CAPTURE_PATH),i.getStringExtra(EXTRA_PREVIEW_MODE));return START_STICKY;}if(ACTION_REFRESH_SETTINGS.equals(a)){refreshBubble(i.getBooleanExtra("resetPosition",false));return START_STICKY;}if(ACTION_START.equals(a)||ACTION_SHOW_BUBBLE.equals(a)){removePreview();showBubble();return START_STICKY;}return START_STICKY;}
    private void showBubble(){if(!Settings.canDrawOverlays(this)||wm==null)return;if(bubble!=null){bubble.setVisibility(View.VISIBLE);scheduleDim();return;}TextView b=new TextView(this);b.setText("◐");b.setTextColor(Color.WHITE);b.setTextSize(22);b.setGravity(Gravity.CENTER);b.setBackground(circle(0xdd555555));int sz=dp(OverlayPrefs.sizeDp(this));bubbleLp=new WindowManager.LayoutParams(sz,sz,overlayType(),WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,android.graphics.PixelFormat.TRANSLUCENT);bubbleLp.gravity=Gravity.TOP|Gravity.START;android.content.SharedPreferences p=getSharedPreferences("bubble",MODE_PRIVATE);bubbleLp.x=p.getInt("x",20);bubbleLp.y=p.getInt("y",dp(180));final float[] down=new float[4];b.setOnTouchListener((v,e)->{wakeBubble();if(e.getAction()==MotionEvent.ACTION_DOWN){down[0]=e.getRawX();down[1]=e.getRawY();down[2]=bubbleLp.x;down[3]=bubbleLp.y;dragging=false;return true;}if(e.getAction()==MotionEvent.ACTION_MOVE){float dx=e.getRawX()-down[0],dy=e.getRawY()-down[1];if(Math.abs(dx)+Math.abs(dy)>dp(8))dragging=true;bubbleLp.x=(int)(down[2]+dx);bubbleLp.y=(int)(down[3]+dy);try{wm.updateViewLayout(bubble,bubbleLp);}catch(Exception ignored){}return true;}if(e.getAction()==MotionEvent.ACTION_UP){if(dragging){snapAndSave();scheduleDim();return true;}long now=System.currentTimeMillis();if(now-lastTap<350){lastTap=0;MacroDroidBridge.restore(this);removePanel();Toast.makeText(this,"원래색",Toast.LENGTH_SHORT).show();}else{lastTap=now;ui.postDelayed(()->{if(lastTap!=0&&System.currentTimeMillis()-lastTap>=330){lastTap=0;togglePanel();}},350);}return true;}return false;});bubble=b;try{wm.addView(bubble,bubbleLp);}catch(Exception e){bubble=null;}setBubbleAlpha(false);scheduleDim();}
    private void togglePanel(){if(panel!=null){removePanel();return;}showPanel();}
    private void showPanel(){if(bubble==null||wm==null)return;LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(6),dp(6),dp(6),dp(6));box.setBackground(roundRect(0xee222222,dp(14)));LinearLayout r1=new LinearLayout(this),r2=new LinearLayout(this);r1.setOrientation(LinearLayout.HORIZONTAL);r2.setOrientation(LinearLayout.HORIZONTAL);addQuick(r1,"↺","원래",v->{MacroDroidBridge.restore(this);removePanel();});addQuick(r1,"흑","흑백",v->{MacroDroidBridge.gray(this);removePanel();});addQuick(r1,"3","3값",v->{removePanel();requestCapture("three");});addQuick(r2,"≈","블러",v->{removePanel();requestCapture("blur");});addQuick(r2,"⇆","좌우",v->{removePanel();requestCapture("mirror");});addQuick(r2,"◐","반전",v->{MacroDroidBridge.invert(this);removePanel();});box.addView(r1);box.addView(r2);WindowManager.LayoutParams lp=new WindowManager.LayoutParams(dp(252),WindowManager.LayoutParams.WRAP_CONTENT,overlayType(),WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE,android.graphics.PixelFormat.TRANSLUCENT);lp.gravity=Gravity.TOP|Gravity.START;int sw=getResources().getDisplayMetrics().widthPixels;lp.x=Math.max(0,Math.min(sw-dp(252),bubbleLp.x-(bubbleLp.x>sw/2?dp(210):0)));lp.y=Math.max(0,bubbleLp.y+dp(OverlayPrefs.sizeDp(this))+dp(6));panel=box;try{wm.addView(panel,lp);}catch(Exception e){panel=null;}}
    private void addQuick(LinearLayout row,String icon,String label,View.OnClickListener l){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setGravity(Gravity.CENTER);c.setPadding(dp(3),dp(3),dp(3),dp(3));TextView i=new TextView(this);i.setText(icon);i.setTextSize(20);i.setTextColor(Color.WHITE);i.setGravity(Gravity.CENTER);TextView t=new TextView(this);t.setText(label);t.setTextSize(10);t.setTextColor(0xffdddddd);t.setGravity(Gravity.CENTER);c.addView(i,new LinearLayout.LayoutParams(dp(36),dp(30)));c.addView(t,new LinearLayout.LayoutParams(dp(38),dp(18)));c.setOnClickListener(l);row.addView(c,new LinearLayout.LayoutParams(dp(78),dp(54)));}
    private void requestCapture(String mode){if(bubble!=null)bubble.setVisibility(View.GONE);Intent x=new Intent(this,CapturePermissionActivity.class);x.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_NO_ANIMATION);x.putExtra(EXTRA_PREVIEW_MODE,mode);startActivity(x);}
    private void showPreview(String path,String mode){removePanel();if(bubble!=null)bubble.setVisibility(View.GONE);removePreview();if(path==null)return;Bitmap src=BitmapFactory.decodeFile(new File(path).getAbsolutePath());if(src==null){showBubble();return;}Bitmap out=BitmapFilters.apply(src,mode==null?"original":mode);if(out!=src)src.recycle();FrameLayout root=new FrameLayout(this);root.setBackgroundColor(Color.BLACK);ImageView img=new ImageView(this);img.setScaleType(ImageView.ScaleType.FIT_CENTER);img.setImageBitmap(out);root.addView(img,new FrameLayout.LayoutParams(-1,-1));LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER);bar.setPadding(dp(4),dp(4),dp(4),dp(4));bar.setBackgroundColor(0xdd111111);String[][] modes={{"원본","original"},{"흑백","gray"},{"저채도","lowSat"},{"2값","two"},{"3값","three"},{"블러","blur"},{"좌우","mirror"},{"축소","thumb"},{"R","r"},{"G","g"},{"B","b"}};for(String[] m:modes){Button b=smallButton(m[0]);b.setOnClickListener(v->{Bitmap fresh=BitmapFactory.decodeFile(path);if(fresh!=null){Bitmap f=BitmapFilters.apply(fresh,m[1]);if(f!=fresh)fresh.recycle();img.setImageBitmap(f);}});bar.addView(b,new LinearLayout.LayoutParams(0,dp(46),1));}Button close=smallButton("닫기");close.setOnClickListener(v->{removePreview();showBubble();});bar.addView(close,new LinearLayout.LayoutParams(0,dp(46),1));FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(-1,dp(54),Gravity.BOTTOM);root.addView(bar,bp);WindowManager.LayoutParams lp=new WindowManager.LayoutParams(-1,-1,overlayType(),WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN,android.graphics.PixelFormat.TRANSLUCENT);lp.gravity=Gravity.TOP|Gravity.START;preview=root;try{wm.addView(preview,lp);}catch(Exception e){preview=null;showBubble();}}
    private Button smallButton(String s){Button b=new Button(this);b.setAllCaps(false);b.setText(s);b.setTextSize(9);b.setPadding(0,0,0,0);return b;}
    private void snapAndSave(){if(bubbleLp==null)return;int sw=getResources().getDisplayMetrics().widthPixels,sh=getResources().getDisplayMetrics().heightPixels,sz=dp(OverlayPrefs.sizeDp(this));bubbleLp.y=Math.max(0,Math.min(sh-sz,bubbleLp.y));if(OverlayPrefs.edgeSnap(this))bubbleLp.x=bubbleLp.x+sz/2<sw/2?0:Math.max(0,sw-sz);try{wm.updateViewLayout(bubble,bubbleLp);}catch(Exception ignored){}getSharedPreferences("bubble",MODE_PRIVATE).edit().putInt("x",bubbleLp.x).putInt("y",bubbleLp.y).apply();}
    private void refreshBubble(boolean reset){if(reset)getSharedPreferences("bubble",MODE_PRIVATE).edit().clear().apply();removePanel();removeBubble();showBubble();}
    private void wakeBubble(){ui.removeCallbacks(dimTask);setBubbleAlpha(false);} private void scheduleDim(){ui.removeCallbacks(dimTask);if(OverlayPrefs.autoDim(this))ui.postDelayed(dimTask,OverlayPrefs.dimDelaySec(this)*1000L);} private void setBubbleAlpha(boolean dim){if(bubble!=null)bubble.setAlpha((dim?OverlayPrefs.dimOpacity(this):OverlayPrefs.opacity(this))/100f);} private void safeRestore(){MacroDroidBridge.restore(this);}
    private void removePanel(){if(panel!=null){try{wm.removeView(panel);}catch(Exception ignored){}panel=null;}} private void removeBubble(){ui.removeCallbacks(dimTask);if(bubble!=null){try{wm.removeView(bubble);}catch(Exception ignored){}bubble=null;}} private void removePreview(){if(preview!=null){try{wm.removeView(preview);}catch(Exception ignored){}preview=null;}} private void removeAll(){removePanel();removePreview();removeBubble();}
    private int overlayType(){return Build.VERSION.SDK_INT>=26?WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY:WindowManager.LayoutParams.TYPE_PHONE;} private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);} private GradientDrawable circle(int color){GradientDrawable d=new GradientDrawable();d.setShape(GradientDrawable.OVAL);d.setColor(color);d.setStroke(dp(1),0x66ffffff);return d;} private GradientDrawable roundRect(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(radius);return d;}
    private void createChannel(){if(Build.VERSION.SDK_INT<26)return;NotificationChannel c=new NotificationChannel(CHANNEL,"ArtTrainer 플로팅",NotificationManager.IMPORTANCE_LOW);NotificationManager n=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(n!=null)n.createNotificationChannel(c);} private Notification notification(){Intent o=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,0,o,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CHANNEL):new Notification.Builder(this);return b.setSmallIcon(R.drawable.ic_arttrainer).setContentTitle("ArtTrainer").setContentText("그림 진단 플로팅 도구 실행 중").setContentIntent(pi).setOngoing(true).build();}
    @Override public void onDestroy(){running=false;safeRestore();removeAll();stopForeground(true);super.onDestroy();} @Override public IBinder onBind(Intent i){return null;}
}
